### ISSUE TITLE
Use madock n98

### ISSUE THREAD

**Issue by jonatanaxe** [faradey/madock#15]
Hi @faradey I have errors when trying to run n98 in some commands

`madock n98 db:dump --strip="@customers @sales @quotes @log @sessions"`
![image](https://github.com/faradey/madock/assets/2486808/94244cac-0a7a-441b-bf75-ef9a77369261)

However, I can run the same command with local n98 inside the container and it works

` bin/magerun2 db:dump --strip="@customers @sales @quotes @log @sessions"`

I had a similar problem with `db:query`

**Comment by faradey** [comment]
Hi, the bug has been confirmed. The error was in escaping double quotes. The bug has been fixed. To verify, please update the build and compile.

**Comment by jonatanaxe** [comment]
> Hi, the bug has been confirmed. The error was in escaping double quotes. The bug has been fixed. To verify, please update the build and compile.

@faradey How quick was that, thank you very much
Fixed
![image](https://github.com/faradey/madock/assets/2486808/47b38c27-7b0f-4c8d-99cd-084701c7fdc7)
