### ISSUE TITLE
SSL Certificate Error

### ISSUE THREAD

**Issue by maria-axe** [faradey/madock#16]
@faradey Hey, how are you? I installed madock at my location and now an ssl certificate error is occurring. The browser is not recognizing it. Have you ever experienced this problem?

![image](https://github.com/faradey/madock/assets/80163994/0a41afb1-86b1-40b7-bee2-971cf186fccf)

**Comment by faradey** [comment]
Hello @maria-axe 
I'm fine, thank you :)

Yes, SSL certificate issues can sometimes occur. I mainly use Google Chrome, and I've also experienced situations where a project doesn't recognize the certificate on the first try.

Please try the following steps to resolve the issue:

1. Run `madock ssl:rebuild`
2. During the execution of the `madock ssl:rebuild` command, you will be prompted to enter a password.
3. After the command is completed, restart your browser.
4. If restarting the browser doesn't help, restart your computer.
5. If the problem persists, please let me know and we'll continue working on the solution.

**Comment by maria-axe** [comment]
I followed these steps:

1. I executed `madock ssl:rebuild`
2. After that, it asked for "certutil" and I installed the library with `sudo apt install libnss3-tools`
3. Then, I executed `madock ssl:rebuild` and `madock rebuild`
5. I restarted the browser

And it worked! Thank you very much for the support.
