### ISSUE TITLE
Magento cache clean

### ISSUE THREAD

**Issue by jonatanaxe** [faradey/madock#17]
Hi @faradey  have you ever used cache-clean on Madock?
Because it requires node and php to run

https://github.com/mage2tv/magento-cache-clean/

**Comment by faradey** [comment]
Hi @jonatanaxe
I've never used such a module. At the moment there is no way to run this in madock, but I know how to fix it :)

**Comment by faradey** [comment]
@jonatanaxe 
you can update madock and run the following commands to use the cache-clean
```
madock composer require --dev mage2tv/magento-cache-clean
```
```
madock service:enable php/nodejs
```
```
madock cli vendor/bin/cache-clean.js --watch
```

**Comment by jonatanaxe** [comment]
@faradey It works very well, thank you
![image](https://github.com/faradey/madock/assets/2486808/1e07c394-99a3-4fe4-a704-a69ce41e7a27)
