### ISSUE TITLE
Warning message .yml

### ISSUE THREAD

**Issue by jonatanaxe** [faradey/madock#18]
Hi @faradey  Have you ever seen this warning message?

```
WARN[0000] /home/USER/madock/aruntime/projects/PROJECT/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
WARN[0000] /home/USER/madock/aruntime/projects/PROJECT/docker-compose.override.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
```

**Comment by faradey** [comment]
Hi @jonatanaxe 
Yes, I noticed them; they started appearing after the Docker kernel update. They don't affect the build process. I'll look into it and try to remove them in the future. Please don't close the issue yet; I'll close it myself once it's fixed.

**Comment by jonatanaxe** [comment]
> Hi @jonatanaxe Yes, I noticed them; they started appearing after the Docker kernel update. They don't affect the build process. I'll look into it and try to remove them in the future. Please don't close the issue yet; I'll close it myself once it's fixed.

Thanks @faradey , no problem, I can still use it normally

**Comment by faradey** [comment]
Hi @jonatanaxe 
the last commit made changes that fixed the .yml files and now the warnings do not appear.
In existing projects, the warnings will disappear only after the madock rebuild command
