### ISSUE TITLE
mac m1

### ISSUE THREAD

**Issue by victorlopescv** [faradey/madock#22]
hello friend!

I'm having problems with the symbolic link, I don't have the same return in $Path. When I type which madock it returns that the command was not found and when I type just madock it opens the madock folder. What could be happening?

**Comment by faradey** [comment]
hello @victorlopescv 
could you specify here the command you use in full?

**Comment by faradey** [comment]
hello @victorlopescv 
I am closing this issue as there is no response from you. If you have any problems, feel free to open a new issue.
