### ISSUE TITLE
RabbitMQ Configuration

### ISSUE THREAD

**Issue by maria-axe** [faradey/madock#23]
Olá, @faradey. How are you?

I'm trying to configure RabbitMQ:

My configuration: 

 'queue' => [
        'amqp' => [
            'host' => 'rabbitmq',
            'port' => '5672',
            'user' => 'magento',
            'password' => 'magento',
            'virtualhost' => '/'
        ],
        'consumers_wait_for_messages' => 1
    ]
    
I encountered this error with this configuration: #62 {main} {"exception":"[object] (PhpAmqpLib\Exception\AMQPIOException(code: 0): stream_socket_client(): Unable to connect to tcp://rabbitmq:15672 (Connection refused) at /var/www/html/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php:108)"} []

**Comment by faradey** [comment]
Hi @maria-axe 
I'm doing great, I hope you're doing great too :)

You can use the following options 
'queue' => [
        'consumers_wait_for_messages' => 1,
        'amqp' => [
            'host' => 'rabbitmq',
            'port' => '5672',
            'user' => 'guest',
            'password' => 'guest',
            'virtualhost' => '/',
            'ssl' => false
        ]
    ]

**Comment by maria-axe** [comment]
It worked out. But, how can I access it through the browser:

example: localhost:5672

**Comment by faradey** [comment]
@maria-axe at the moment there is no browser access.
Could you please tell me for what purposes you need such access and maybe I can suggest a quick solution?
