### ISSUE TITLE
Grunt Configuration (Less)

### ISSUE THREAD

**Issue by maria-axe** [faradey/madock#24]
Hi @faradey. Good morning!

I wanted to answer some questions about grunt configuration. I'm following the documentation, but when I run Grunt, it gives this error. Do you know what it could be?

![image](https://github.com/user-attachments/assets/955563ec-95ac-4cba-8afb-8a5fd679d29e)

**Comment by faradey** [comment]
Hi @maria-axe 
Could you please provide your `config.xml` file from the project folder located at `madock/projects/{project-name}`?

**Comment by faradey** [comment]
I think I know the cause of your problem. You are using the `NodeJs` service, but it doesn't contain PHP. Therefore, you need to disable the `NodeJs` service and enable the `php/nodejs` service with the following commands:

```bash
madock service:disable nodejs
madock service:enable php/nodejs
```

**Comment by maria-axe** [comment]
Hi @faradey It worked after adding a new version of Node.js. I made a modification to the Dockerfile in the PHP container for Magento 2.

```
<<<if{{{php/nodejs/enabled}}}>>> 
RUN curl -fsSL https://deb.nodesource.com/setup_{{{php/nodejs/version}}}.x  | bash - && \
    apt-get install -y nodejs
RUN mkdir /var/www/.npm && chown {{{os/user/uid}}}:{{{os/user/guid}}} /var/www/.npm

RUN chown -R {{{os/user/uid}}}:{{{os/user/guid}}} /usr/lib/node_modules

RUN npm install -g grunt-cli

RUN chown -R {{{os/user/uid}}}:{{{os/user/guid}}} /usr/bin
<<<endif>>>
```

Additionally, I created the configuration to dynamically add the version.

```
<nodejs>
    <enabled>true</enabled>
    <version>18</version>
</nodejs>
```

**Comment by faradey** [comment]
Hi @maria-axe 
That's great!  
I'm a backend developer and rarely use `grunt-cli`, so I might have missed some specifics.  
Usually, with Node.js installed in the PHP container, grunt can be installed using the command:  
```bash
madock node npm ...
```  
But your approach is also completely valid.  
I'm really glad you found your way and demonstrated that the build process is flexible in its setup when the situation requires it.
