### ISSUE TITLE
Add post dump command to fix DEFINER

### ISSUE THREAD

**Issue by artmouse** [faradey/madock#5]
Execute after db:export
```
's/DEFINER[ ]*=[ ]*`[^`]+`@`[^`]+`/DEFINER=CURRENT_USER/g'
```

**Comment by faradey** [comment]
there is such an expression s/DEFINER[ ]*=[ ]*[^*]*\*/\*/ before import.
Perhaps it will be enough to apply this expression after the export?

**Comment by faradey** [comment]
Removing a username from a database dump on export has been added and tested.
https://github.com/faradey/madock/commit/9784dc770e568e97bb60f55db561e448adfeec3a
