### ISSUE TITLE
Incorrect phrase for domain input

### ISSUE THREAD

**Issue by artmouse** [faradey/madock#9]
If you select custom for host, the data entry phrase asks for "version", which is misleading.
I suggest replacing it with a more appropriate phrase with an example format.

![image](https://github.com/faradey/madock/assets/527232/cc69651f-5d98-415b-b8fc-9b277d796af9)

**Comment by faradey** [comment]
Hello,
Yes, you are right. If we want to enter a custom value, the command should be “Enter the custom value”.
